name: Continuous Build analysis

on:
  push:
    branches:
      - master

jobs:

  build:
    name : build developement branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '17'

        - name: Maven Build & Sonar analysis
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
